# Processed E-commerce Dataset

In [1]:
import pandas as pd

orders = pd.read_csv("Orders.csv")
customers = pd.read_csv("Customers.csv")
products = pd.read_csv("Products.csv")

print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

In [2]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [3]:
customers.head()

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [4]:
products.head()

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

## Merge Orders and Customers

The `Customer_ID` column is common in both datasets.

In [5]:
orders_customers = orders.merge(
    customers,
    on="Customer_ID",
    how="left"
)

orders_customers.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

## Merge Product Information

In [6]:
processed = orders_customers.merge(
    products,
    on="Product_ID",
    how="left"
)

processed.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

## Using concat()

In [7]:
orders_part1 = orders.iloc[:5]
orders_part2 = orders.iloc[5:10]

combined_orders = pd.concat([orders_part1, orders_part2])

combined_orders

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped

## Convert Order Date

In [8]:
processed["Order_Date"] = pd.to_datetime(processed["Order_Date"])

processed[["Order_ID", "Order_Date"]].head()

  Order_ID Order_Date
0    O0001 2026-02-19
1    O0002 2026-01-25
2    O0003 2026-02-26
3    O0004 2026-03-04
4    O0005 2026-03-29

## Extract Month, Day and Day of Week

In [9]:
processed["Month"] = processed["Order_Date"].dt.month
processed["Day"] = processed["Order_Date"].dt.day
processed["Day_of_Week"] = processed["Order_Date"].dt.day_name()

processed[[
    "Order_ID",
    "Order_Date",
    "Month",
    "Day",
    "Day_of_Week"
]].head()

  Order_ID Order_Date  Month  Day Day_of_Week
0    O0001 2026-02-19      2   19    Thursday
1    O0002 2026-01-25      1   25      Sunday
2    O0003 2026-02-26      2   26    Thursday
3    O0004 2026-03-04      3    4   Wednesday
4    O0005 2026-03-29      3   29      Sunday

## Using apply()

I used `apply()` to calculate the total amount for each order.

**Total Amount = Quantity × Unit Price**

In [10]:
processed["Total_Amount"] = processed.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

processed[[
    "Order_ID",
    "Product_Name",
    "Quantity",
    "Unit_Price",
    "Total_Amount"
]].head(10)

  Order_ID             Product_Name  Quantity  Unit_Price  Total_Amount
0    O0001              Cricket Bat         2        2499          4998
1    O0002           Wireless Mouse         2         899          1798
2    O0003              Smart Watch         1        3299          3299
3    O0004  Machine Learning Basics         3         999          2997
4    O0005             Coffee Maker         5        3499         17495
5    O0006                 Football         3         799          2397
6    O0007           Wireless Mouse         3         899          2697
7    O0008               Power Bank         4        1199          4796
8    O0009             Coffee Maker         2        3499          6998
9    O0010               Power Bank         2        1199          2398

## Create the Final Clean DataFrame

In [11]:
processed = processed[
    [
        "Order_ID", "Order_Date", "Month", "Day", "Day_of_Week",
        "Customer_ID", "Customer_Name", "City", "Region",
        "Membership_Type", "Product_ID", "Product_Name",
        "Category", "Brand", "Unit_Price", "Quantity",
        "Total_Amount", "Payment_Method", "Order_Status"
    ]
]

processed.head()

,Order_ID,Order_Date,Month,Day,Day_of_Week,Customer_ID,Customer_Name,City,Region,Membership_Type,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,2,19,Thursday,C027,Harsh Vardhan,Noida,North,Premium,P019,Cricket Bat,Sports,BatPro,2499,2,4998,Credit Card,Delivered
1,O0002,2026-01-25,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,Premium,P003,Wireless Mouse,Electronics,TechGear,899,2,1798,Debit Card,Delivered
2,O0003,2026-02-26,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,Regular,P004,Smart Watch,Electronics,FitTech,3299,1,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,Regular,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Net Banking,Delivered
4,O0005,2026-03-29,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,New,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,Credit Card,Delivered

## Check the Final Dataset

In [12]:
print("Shape:", processed.shape)
print("\nColumns:")
print(processed.columns.tolist())

Shape: (120, 19)

Columns:
['Order_ID', 'Order_Date', 'Month', 'Day', 'Day_of_Week', 'Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_ID', 'Product_Name', 'Category', 'Brand', 'Unit_Price', 'Quantity', 'Total_Amount', 'Payment_Method', 'Order_Status']

In [13]:
processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         120 non-null    object
 1   Order_Date       120 non-null    datetime64[ns]
 2   Month            120 non-null    int32
 3   Day              120 non-null    int32
 4   Day_of_Week      120 non-null    object
 5   Customer_ID      120 non-null    object
 6   Customer_Name    120 non-null    object
 7   City             120 non-null    object
 8   Region           120 non-null    object
 9   Membership_Type  120 non-null    object
 10  Product_ID       120 non-null    object
 11  Product_Name     120 non-null    object
 12  Category         120 non-null    object
 13  Brand            120 non-null    object
 14  Unit_Price       120 non-null    int64
 15  Quantity         120 non-null    int64
 16  Total_Amount     120 non-null    int64
 17  Payment_Method   120 non-null    object
 18  Order_Status     120 non-null    object
dtypes: datetime64[ns](1), int32(2), int64(3), object(13)
memory usage: 17.0+ KB

In [14]:
processed.isnull().sum()

Order_ID           0
Order_Date         0
Month              0
Day                0
Day_of_Week        0
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
Product_ID         0
Product_Name       0
Category           0
Brand              0
Unit_Price         0
Quantity           0
Total_Amount       0
Payment_Method     0
Order_Status       0
dtype: int64

## Some Simple Checks on the Processed Data

In [15]:
# Total sales amount
print("Total Amount:", processed["Total_Amount"].sum())

# Total quantity
print("Total Quantity:", processed["Quantity"].sum())

# Number of orders
print("Number of Orders:", processed["Order_ID"].nunique())

Total Amount: 741507
Total Quantity: 343
Number of Orders: 120

In [16]:
# Orders by day of week
processed["Day_of_Week"].value_counts()

Day_of_Week
Thursday     20
Friday       20
Sunday       18
Tuesday      17
Monday       17
Wednesday    14
Saturday     14
Name: count, dtype: int64

## Export the Processed Dataset

In [17]:
processed.to_csv(
    "Day9_Processed_Ecommerce_Dataset.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

## Observations

- The three datasets were successfully combined using `merge()`.
- Customer and product details are now available along with each order.
- `concat()` was used to demonstrate combining DataFrames vertically.
- The order date was converted to DateTime format and month, day and day of week were extracted.
- `apply()` was used to calculate the total amount for each order.
- The final dataset is more useful because order, customer and product information is available in one DataFrame.
- The processed data was exported as a CSV file for further use.